# Generated by Django 3.2.6 on 2021-08-27 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0004_auto_20210827_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="approval_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
