# Generated by Django 5.2 on 2025-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="authorized_only",
            field=models.BooleanField(
                default=False,
                help_text="Czy post jest dostępny tylko dla zalogowanych użytkowników?",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Czy post jest ukryty - nie będzie wyświetlany na liście postów.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(
                default=False, help_text="Czy post jest przypięty na stronie głównej?"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Priorytet postu (wyższy priorytet = wyższa pozycja na liście)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "draft"), (1, "published"), (2, "archived")], default=0
            ),
        ),
    ]
