services:
  backend:
    depends_on:
      - db
    build: ./eproba
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - backup_volume:/home/app/web/backups
      - ./secrets/firebase-admin-sdk.json:/home/app/web/firebase-admin-sdk.json
    networks:
      - app-network
    expose:
      - 8000
    env_file:
      - ./.env
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=${TZ}
      - PGTZ=${TZ}
  nginx:
    depends_on:
      - backend
    image: nginx:1.27.1-alpine
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx-conf:/etc/nginx/conf.d
    #      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network
    environment:
      - TZ=${TZ}
    ports:
      - "80:80"
#      - "443:443"
#  certbot:
#    depends_on:
#      - nginx
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#    command: certonly --email eproba@zhr.pl --agree-tos --no-eff-email --staging -d eproba.zhr.pl -d www.eproba.zhr.pl


volumes:
  postgres_data:
  static_volume:
  backup_volume:
#  certbot-etc:

networks:
  app-network:
    driver: bridge
