# Generated by Django 5.1.6 on 2025-02-09 01:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_is_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TeamRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Zgłoszone"),
                            ("approved", "Zaakceptowane"),
                            ("rejected", "Odrzucone"),
                            (
                                "pending_verification",
                                "Oczekuje na dodatkową weryfikację",
                            ),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "function_level",
                    models.IntegerField(
                        choices=[
                            (3, "Przyboczny"),
                            (4, "Drużynowy"),
                            (5, "Wyższa funkcja"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField()),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_team_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie drużyny",
                "verbose_name_plural": "Zgłoszenia drużyn",
            },
        ),
    ]
