# Generated by Django 5.1.6 on 2025-02-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_is_verified_teamrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patrol",
            name="team",
            field=models.ForeignKey(
                default="a0f04e13-53a9-4511-afe1-2459786e3788",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patrols",
                to="teams.team",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="district",
            field=models.ForeignKey(
                default="083d9744-e95e-4d96-bb4c-2dfff329b7f4",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="teams",
                to="teams.district",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="short_name",
            field=models.CharField(max_length=20),
        ),
    ]
