# Generated by Django 5.1.6 on 2025-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_patrol_team_alter_team_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamrequest",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
