# Generated by Django 5.1.6 on 2025-02-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_teamrequest_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="organization",
            field=models.IntegerField(
                choices=[(0, "Organizacja Harcerzy"), (1, "Organizacja Harcerek")],
                default=0,
            ),
        ),
    ]
