# Generated by Django 4.1.5 on 2023-01-19 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="colors",
        ),
    ]
