# Generated by Django 5.1 on 2024-08-15 14:01

import uuid

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("nickname", models.CharField(max_length=20)),
                ("first_name", models.CharField(blank=True, max_length=20, null=True)),
                ("last_name", models.CharField(blank=True, max_length=40, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "scout_rank",
                    models.IntegerField(
                        choices=[
                            (0, "brak stopnia"),
                            (1, '"biszkopt"'),
                            (2, "mł."),
                            (3, "wyw."),
                            (4, "ćwik"),
                            (5, "HO"),
                            (6, "HR"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "instructor_rank",
                    models.IntegerField(
                        choices=[
                            (0, "brak stopnia"),
                            (1, "pwd."),
                            (2, "phm."),
                            (3, "hm."),
                        ],
                        default=0,
                    ),
                ),
                (
                    "function",
                    models.IntegerField(
                        choices=[
                            (0, "Druh"),
                            (1, "Podzastępowy"),
                            (2, "Zastępowy"),
                            (3, "Przyboczny"),
                            (4, "Drużynowy"),
                            (5, "Wyższa funkcja"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "patrol",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="teams.patrol",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Użytkownik",
                "verbose_name_plural": "Użytkownicy",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
