# Generated by Django 3.2.6 on 2021-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scout",
            name="function",
            field=models.IntegerField(
                choices=[
                    (0, "Druh"),
                    (1, "Podzastępowy"),
                    (2, "Zastępowy."),
                    (3, "Przyboczny"),
                    (4, "Drużynowy"),
                    (5, "Wyższa funkcja"),
                ],
                default=0,
            ),
        ),
    ]
