# Generated by Django 4.1 on 2022-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_scout_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="scout",
            name="instructor_rank",
            field=models.IntegerField(
                choices=[(0, "brak stopnia"), (1, "pwd."), (2, "phm."), (3, "hm.")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="scout",
            name="scout_rank",
            field=models.IntegerField(
                choices=[
                    (0, "brak stopnia"),
                    (1, '"biszkopt"'),
                    (2, "mł."),
                    (3, "wyw."),
                    (4, "ćwik"),
                    (5, "HO"),
                    (6, "HR"),
                ],
                default=0,
            ),
        ),
    ]
