# Generated by Django 4.1 on 2022-09-11 14:27

from django.db import migrations
from django.db.migrations import RunPython


def detect_rank(apps, schema_editor):
    Scout = apps.get_model("users", "Scout")
    for scout in Scout.objects.all():
        if scout.rank == " ":
            scout.scout_rank = 0
        elif scout.rank == "mł.":
            scout.scout_rank = 2
        elif scout.rank == "wyw.":
            scout.scout_rank = 3
        elif scout.rank == "ćwik":
            scout.scout_rank = 4
        elif scout.rank == "HO":
            scout.scout_rank = 5
        elif scout.rank == "pwd. HO":
            scout.scout_rank = 5
            scout.instructor_rank = 1
        elif scout.rank == "HR":
            scout.scout_rank = 6
        elif scout.rank == "pwd. HR":
            scout.scout_rank = 6
            scout.instructor_rank = 1
        elif scout.rank == "phm. HR":
            scout.scout_rank = 6
            scout.instructor_rank = 2
        elif scout.rank == "hm. HR":
            scout.scout_rank = 6
            scout.instructor_rank = 3
        scout.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_add_scout_scout_rank_and_instructor_rank"),
    ]

    operations = [RunPython(detect_rank)]
