# Generated by Django 4.1.5 on 2023-01-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_remove_team_colors"),
        ("users", "0010_remove_scout_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scout",
            name="patrol",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="scouts",
                to="teams.patrol",
            ),
        ),
    ]
