# Generated by Django 3.1.7 on 2021-02-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20201129_2303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scout",
            name="initials",
        ),
    ]
