# Generated by Django 5.0.6 on 2024-06-29 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_scout_patrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("users", "Konkretni użytkownicy"),
                            (
                                "users_exclude",
                                "Wszyscy oprócz konkretnych użytkowników",
                            ),
                            ("all", "Wszyscy użytkownicy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "targets",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
