# Generated by Django 5.1.6 on 2025-02-27 18:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_team_organization"),
        ("worksheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worksheet",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Opis próby"),
        ),
        migrations.CreateModel(
            name="TemplateWorksheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Organizacja Harcerzy"),
                            (1, "Organizacja Harcerek"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa szablonu"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Opis szablonu"
                    ),
                ),
                (
                    "template_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notatki do szablonu"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Szablon",
                "verbose_name_plural": "Szablony",
            },
        ),
        migrations.CreateModel(
            name="TemplateTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task",
                    models.CharField(max_length=250, verbose_name="Zadanie szablonu"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Opis zadania szablonu"
                    ),
                ),
                (
                    "template_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Notatki do zadania szablonu",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="worksheets.templateworksheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie szablonu",
                "verbose_name_plural": "Zadania szablonu",
            },
        ),
    ]
