# Generated by Django 5.1.6 on 2025-02-27 18:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_templates(apps, schema_editor):
    # Get historical versions of the models
    Worksheet = apps.get_model("worksheets", "Worksheet")
    Task = apps.get_model("worksheets", "Task")
    TemplateWorksheet = apps.get_model("worksheets", "TemplateWorksheet")
    TemplateTask = apps.get_model("worksheets", "TemplateTask")

    # For each Worksheet that was marked as a template, create a new Template instance and remove the old Worksheet.
    for worksheet in Worksheet.objects.filter(is_template=True, deleted=False):
        # Determine the team. If your User model has a team attribute, use it;
        # otherwise, use the first available Team (or adjust as needed).
        if hasattr(worksheet.user, "patrol") and worksheet.user.patrol:
            team_instance = worksheet.user.patrol.team
        else:
            continue  # Skip this worksheet if the user doesn’t have a team

        new_template = TemplateWorksheet.objects.create(
            id=worksheet.id,
            team=team_instance,
            name=worksheet.name,
            description="",  # Old templates didn’t have a description; default to empty
            created_at=worksheet.updated_at,
            # Use the updated_at as the creation time as created_at didn’t exist before
            updated_at=worksheet.updated_at,
        )

        # Now, migrate all tasks related to the worksheet into TemplateTask records.
        tasks = Task.objects.filter(worksheet=worksheet)
        for task in tasks:
            TemplateTask.objects.create(
                id=task.id,
                template=new_template,
                task=task.task,
                description=task.description,
            )

    # Remove all migrated Template and TemplateTask records.
    Worksheet.objects.filter(is_template=True).delete()


class Migration(migrations.Migration):

    replaces = [
        ("worksheets", "0002_worksheet_created_at_worksheet_description_and_more"),
        ("worksheets", "0003_migrate_templates"),
        ("worksheets", "0004_remove_worksheet_is_template_and_more"),
    ]

    dependencies = [
        ("teams", "0006_team_organization"),
        ("worksheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worksheet",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Opis próby"),
        ),
        migrations.CreateModel(
            name="TemplateWorksheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Organizacja Harcerzy"),
                            (1, "Organizacja Harcerek"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa szablonu"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Opis szablonu"
                    ),
                ),
                (
                    "template_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notatki do szablonu"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Szablon",
                "verbose_name_plural": "Szablony",
            },
        ),
        migrations.CreateModel(
            name="TemplateTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task",
                    models.CharField(max_length=250, verbose_name="Zadanie szablonu"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Opis zadania szablonu"
                    ),
                ),
                (
                    "template_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Notatki do zadania szablonu",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="worksheets.templateworksheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie szablonu",
                "verbose_name_plural": "Zadania szablonu",
            },
        ),
        migrations.RunPython(
            code=migrate_templates,
        ),
        migrations.RemoveField(
            model_name="worksheet",
            name="is_template",
        ),
        migrations.AlterField(
            model_name="templateworksheet",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="teams.team",
            ),
        ),
    ]
