# Generated by Django 5.1.6 on 2025-02-27 18:47


import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0003_migrate_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worksheet",
            name="is_template",
        ),
        migrations.AlterField(
            model_name="templateworksheet",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="teams.team",
            ),
        ),
    ]
