# Generated by Django 5.2 on 2025-06-23 12:53

import apps.worksheets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0005_task_category_task_notes_task_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateworksheet",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Obsługiwane formaty: JPG, PNG, SVG. Maksymalny rozmiar: 5MB",
                null=True,
                upload_to=apps.worksheets.models.template_image_upload_path,
                validators=[apps.worksheets.models.validate_template_image],
                verbose_name="Obrazek szablonu",
            ),
        ),
        migrations.AddField(
            model_name="worksheet",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worksheets",
                to="worksheets.templateworksheet",
                verbose_name="Szablon próby",
            ),
        ),
    ]
