# Generated by Django 5.2 on 2025-06-25 07:33

import apps.worksheets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0006_templateworksheet_image_worksheet_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateworksheet",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Obsługiwane formaty: JPG, PNG, SVG oraz GIF. Maksymalny rozmiar: 5MB",
                null=True,
                upload_to=apps.worksheets.models.template_image_upload_path,
                validators=[apps.worksheets.models.validate_template_image],
                verbose_name="Obrazek szablonu",
            ),
        ),
    ]
