# Generated by Django 5.2.3 on 2025-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0007_alter_templateworksheet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetask",
            name="task",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Zadanie szablonu"
            ),
        ),
    ]
