# Generated by Django 5.2.3 on 2025-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0008_alter_templatetask_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="final_challenge",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Próba końcowa (bieg)",
            ),
        ),
        migrations.AddField(
            model_name="worksheet",
            name="final_challenge_description",
            field=models.TextField(
                blank=True, default="", verbose_name="Opis próby końcowej (biegu)"
            ),
        ),
        migrations.AlterField(
            model_name="worksheet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data utworzenia próby"
            ),
        ),
        migrations.AlterField(
            model_name="worksheet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data ostatniej aktualizacji próby"
            ),
        ),
    ]
