# Generated by Django 5.2.5 on 2025-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0009_worksheet_final_challenge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateworksheet",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Szablony o wyższym priorytecie będą wyświetlane wyżej na liście.",
                verbose_name="Priorytet szablonu",
            ),
        ),
    ]
