# Generated by Django 5.2.5 on 2025-08-13 17:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0010_templateworksheet_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateTaskGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Wyświetlana nazwa grupy zadań",
                        max_length=120,
                        verbose_name="Nazwa grupy",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Instrukcja / kontekst dla użytkownika",
                        verbose_name="Opis",
                    ),
                ),
                (
                    "min_tasks",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Minimalna liczba zadań do wybrania (puste = brak)",
                        null=True,
                        verbose_name="Minimalny wybór",
                    ),
                ),
                (
                    "max_tasks",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maksymalna liczba zadań (puste = brak limitu)",
                        null=True,
                        verbose_name="Maksymalny wybór",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_groups",
                        to="worksheets.templateworksheet",
                        verbose_name="Szablon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupa zadań szablonu",
                "verbose_name_plural": "Grupy zadań szablonu",
            },
        ),
        migrations.AddField(
            model_name="templatetask",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcjonalna grupa z ograniczeniami wyboru",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="worksheets.templatetaskgroup",
                verbose_name="Grupa zadań szablonu",
            ),
        ),
    ]
