# Generated by Django 5.2.7 on 2025-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0011_templatetaskgroup_templatetask_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(max_length=1000, verbose_name="Zadanie"),
        ),
        migrations.AlterField(
            model_name="templatetask",
            name="task",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Zadanie szablonu"
            ),
        ),
    ]
