# Generated by Django 5.2.3 on 2025-07-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="page",
            name="district",
        ),
        migrations.RemoveField(
            model_name="page",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="page",
            name="patrol",
        ),
        migrations.RemoveField(
            model_name="page",
            name="team",
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
