# Generated by Django 4.0.5 on 2022-06-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="minimum_function",
            field=models.IntegerField(
                choices=[
                    (0, "Druh"),
                    (1, "Podzastępowy"),
                    (2, "Zastępowy"),
                    (3, "Przyboczny"),
                    (4, "Drużynowy"),
                    (5, "Wyższa funkcja"),
                ],
                default=0,
            ),
        ),
    ]
