# Generated by Django 3.2.6 on 2021-08-27 07:16

from django.db import migrations


def detect_task_state(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Task = apps.get_model("exam", "Task")
    for task in Task.objects.all():
        if task.is_done:
            task.status = 2
        elif task.is_await:
            task.status = 1
        else:
            task.status = 0
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_auto_20210825_2145"),
    ]

    operations = [
        migrations.RunPython(detect_task_state),
    ]
