# Generated by Django 3.1.7 on 2021-02-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_freeday'),
        ('exam', '0003_auto_20210224_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver', to='users.scout'),
        ),
    ]
