# Generated by Django 3.2.6 on 2021-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exam', '0003_auto_20210827_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_await',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'Do zrobienia'), (1, 'Oczekuje na zatwierdzenie'), (2, 'Zatwierdzono'), (3, 'Odrzucono')],
                default=0),
        ),
    ]
