# Generated by Django 3.2.6 on 2021-08-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_task_approval_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SentTask",
        ),
    ]
