# Generated by Django 3.1.7 on 2021-02-25 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exam", "0006_remove_task_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_await",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name="SentTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data wysłania prośby",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="exam.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
