# Generated by Django 3.2.8 on 2021-10-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210827_1246"),
        ("exam", "0006_delete_senttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="supervisor",
                to="users.scout",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="exam",
            name="scout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="scout",
                to="users.scout",
            ),
            preserve_default=False,
        ),
    ]
