# Generated by Django 4.0 on 2021-12-21 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20211111_2141"),
        ("exam", "0010_alter_task_approval_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_archived",
            field=models.BooleanField(
                default=False, verbose_name="Próba zarchiwizowana?"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nazwa próby"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="scout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="scout",
                to="users.scout",
                verbose_name="Właściciel próby",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="supervisor",
                to="users.scout",
                verbose_name="Opiekun próby",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="approval_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Data zatwierdzenia",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approver",
                to="users.scout",
                verbose_name="Zatwierdzający",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Opis zadania"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Do zrobienia"),
                    (1, "Oczekuje na zatwierdzenie"),
                    (2, "Zatwierdzono"),
                    (3, "Odrzucono"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(max_length=250, verbose_name="Zadanie"),
        ),
    ]
