# Generated by Django 4.0.2 on 2022-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0011_exam_is_archived_alter_exam_name_alter_exam_scout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_template",
            field=models.BooleanField(default=False, verbose_name="Szablon?"),
        ),
    ]
