# Generated by Django 4.0.4 on 2022-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0012_exam_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(blank=True, null=True, verbose_name="Kolejność"),
        ),
    ]
