# Generated by Django 4.1.3 on 2022-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0012_exam_is_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Usunięta?"),
        ),
        migrations.AddField(
            model_name="exam",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
