# Generated by Django 4.1.3 on 2022-12-07 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0013_exam_deleted_exam_modification_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="modification_date",
            new_name="updated_at",
        ),
    ]
