# Generated by Django 5.0.6 on 2024-07-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0014_rename_modification_date_exam_updated_at"),
        ("users", "0012_endmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="scout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="exams",
                to="users.scout",
                verbose_name="Właściciel próby",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="supervised_exams",
                to="users.scout",
                verbose_name="Opiekun próby",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tasks",
                to="users.scout",
                verbose_name="Zatwierdzający",
            ),
        ),
    ]
