name: Check lint

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install black
        run: pip install black

      - name: Check black
        run: black --check .

      - name: Install isort
        run: pip install isort

      - name: Check isort
        run: isort --profile black . --check-only
